-- AutoCare Intelligence — Enterprise Data Warehouse DDL
-- File: 01_dimensions.sql
-- Target Database: PostgreSQL 16+
-- Tables: Exactly 6 Conformed Dimensions mandated by AutoCare_Intelligence.pdf Section 7:
--         dim_date, dim_model, dim_dealer, dim_customer, dim_component, dim_vehicle

-- ============================================================================
-- 1. dim_date (Conformed Calendar Dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS autocare_dw.dim_date (
    date_key INT PRIMARY KEY,
    calendar_date DATE UNIQUE NOT NULL,
    day_of_week INT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    day_name VARCHAR(16) NOT NULL,
    day_of_month INT NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
    day_of_year INT NOT NULL CHECK (day_of_year BETWEEN 1 AND 366),
    week_of_year INT NOT NULL CHECK (week_of_year BETWEEN 1 AND 53),
    month_number INT NOT NULL CHECK (month_number BETWEEN 1 AND 12),
    month_name VARCHAR(16) NOT NULL,
    quarter INT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    year INT NOT NULL,
    is_weekend BOOLEAN NOT NULL
);

COMMENT ON TABLE autocare_dw.dim_date IS 'Conformed calendar date dimension for temporal rollups and fiscal filtering.';

-- ============================================================================
-- 2. dim_model (Commercial Vehicle Model Dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS autocare_dw.dim_model (
    model_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(64) UNIQUE NOT NULL,
    vehicle_class VARCHAR(32) NOT NULL,
    powertrain_type VARCHAR(32) NOT NULL,
    fuel_capacity_or_kwh NUMERIC(6,2) NOT NULL CHECK (fuel_capacity_or_kwh >= 0.0),
    curb_weight_kg NUMERIC(8,2) NOT NULL CHECK (curb_weight_kg >= 0.0)
);

COMMENT ON TABLE autocare_dw.dim_model IS 'OEM commercial vehicle model specifications and engineering classifications.';

-- ============================================================================
-- 3. dim_dealer (Dealership Facility Dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS autocare_dw.dim_dealer (
    dealer_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealer_id VARCHAR(32) UNIQUE NOT NULL,
    dealer_name VARCHAR(128) NOT NULL,
    city VARCHAR(64) NOT NULL,
    state VARCHAR(32) NOT NULL,
    region VARCHAR(32) NOT NULL,
    tier VARCHAR(16) NOT NULL
);

COMMENT ON TABLE autocare_dw.dim_dealer IS 'Authorized OEM dealership facilities, workshops, and regional sales hubs.';

-- ============================================================================
-- 4. dim_customer (Customer Dimension — Supporting Ownership Mapping)
-- ============================================================================
CREATE TABLE IF NOT EXISTS autocare_dw.dim_customer (
    customer_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(32) UNIQUE NOT NULL,
    customer_name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(64) NOT NULL,
    state VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE autocare_dw.dim_customer IS 'Registered vehicle owners and fleet accounts linked via registration mapping.';

-- ============================================================================
-- 5. dim_component (Automotive Subsystem & Component Dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS autocare_dw.dim_component (
    component_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_name VARCHAR(64) UNIQUE NOT NULL,
    category VARCHAR(64) NOT NULL,
    expected_lifespan_km INT NOT NULL CHECK (expected_lifespan_km >= 0),
    warranty_period_months INT NOT NULL CHECK (warranty_period_months >= 0)
);

COMMENT ON TABLE autocare_dw.dim_component IS 'Standardized vehicular subsystems and assemblies (Cooling, Powertrain, Electrical, Braking, etc.).';

-- ============================================================================
-- 6. dim_vehicle (Fleet Vehicle Dimension)
-- ============================================================================
CREATE TABLE IF NOT EXISTS autocare_dw.dim_vehicle (
    vehicle_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id VARCHAR(32) UNIQUE NOT NULL,
    model_key INT NOT NULL REFERENCES autocare_dw.dim_model(model_key) ON DELETE RESTRICT,
    customer_key INT NOT NULL REFERENCES autocare_dw.dim_customer(customer_key) ON DELETE RESTRICT,
    selling_dealer_key INT NOT NULL REFERENCES autocare_dw.dim_dealer(dealer_key) ON DELETE RESTRICT,
    variant VARCHAR(32) NOT NULL,
    manufacture_date DATE NOT NULL,
    manufacture_year INT NOT NULL CHECK (manufacture_year >= 1900),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
);

COMMENT ON TABLE autocare_dw.dim_vehicle IS 'Connected fleet vehicles with conformed foreign keys to model, customer, and selling dealer.';

-- ============================================================================
-- 7. Default Unknown Dimension Members (-1)
-- ============================================================================

-- Seed Unknown Member for dim_date
INSERT INTO autocare_dw.dim_date (
    date_key, calendar_date, day_of_week, day_name, day_of_month, day_of_year,
    week_of_year, month_number, month_name, quarter, year, is_weekend
) VALUES (
    -1, '1900-01-01', 1, 'Monday', 1, 1, 1, 1, 'January', 1, 1900, FALSE
) ON CONFLICT (date_key) DO NOTHING;

-- Seed Unknown Member for dim_model
INSERT INTO autocare_dw.dim_model (
    model_key, model_name, vehicle_class, powertrain_type, fuel_capacity_or_kwh, curb_weight_kg
) VALUES (
    -1, 'UNKNOWN MODEL', 'UNKNOWN', 'UNKNOWN', 0.0, 0.0
) ON CONFLICT (model_key) DO NOTHING;

-- Seed Unknown Member for dim_dealer
INSERT INTO autocare_dw.dim_dealer (
    dealer_key, dealer_id, dealer_name, city, state, region, tier
) VALUES (
    -1, 'UNKNOWN_DLR', 'UNKNOWN DEALER', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN'
) ON CONFLICT (dealer_key) DO NOTHING;

-- Seed Unknown Member for dim_customer
INSERT INTO autocare_dw.dim_customer (
    customer_key, customer_id, customer_name, email, phone, address, city, state
) VALUES (
    -1, 'UNKNOWN_CUST', 'UNKNOWN CUSTOMER', 'unknown@autocare.local', '000-000-0000', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN'
) ON CONFLICT (customer_key) DO NOTHING;

-- Seed Unknown Member for dim_component
INSERT INTO autocare_dw.dim_component (
    component_key, component_name, category, expected_lifespan_km, warranty_period_months
) VALUES (
    -1, 'UNKNOWN COMPONENT', 'UNKNOWN', 0, 0
) ON CONFLICT (component_key) DO NOTHING;

-- Seed Unknown Member for dim_vehicle
INSERT INTO autocare_dw.dim_vehicle (
    vehicle_key, vehicle_id, model_key, customer_key, selling_dealer_key,
    variant, manufacture_date, manufacture_year, status
) VALUES (
    -1, 'UNKNOWN_VH', -1, -1, -1, 'UNKNOWN', '1900-01-01', 1900, 'UNKNOWN'
) ON CONFLICT (vehicle_key) DO NOTHING;
