-- AutoCare Intelligence — Enterprise Data Warehouse DDL
-- File: 02_facts.sql
-- Target Database: PostgreSQL 16+
-- Tables: Exactly 4 Conformed Fact Tables mandated by AutoCare_Intelligence.pdf Section 7:
--         fact_telemetry, fact_service, fact_warranty, fact_parts

-- ============================================================================
-- 1. fact_telemetry (High-Frequency IoT Sensor Readings)
-- ============================================================================
-- Grain: 1 row per vehicle per CAN bus sensor reporting timestamp instant.
CREATE TABLE IF NOT EXISTS autocare_dw.fact_telemetry (
    telemetry_fact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_key INT NOT NULL REFERENCES autocare_dw.dim_vehicle(vehicle_key) ON DELETE RESTRICT,
    date_key INT NOT NULL REFERENCES autocare_dw.dim_date(date_key) ON DELETE RESTRICT,
    timestamp TIMESTAMPTZ NOT NULL,
    rpm INT NOT NULL CHECK (rpm >= 0 AND rpm <= 9000),
    temperature NUMERIC(5,2) NOT NULL CHECK (temperature >= -40.0 AND temperature <= 160.0),
    battery NUMERIC(4,2) NOT NULL CHECK (battery >= 9.0 AND battery <= 16.0),
    vibration NUMERIC(6,3) NOT NULL CHECK (vibration >= 0.0 AND vibration <= 15.0),
    _silver_batch_id VARCHAR(64),
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE autocare_dw.fact_telemetry IS 'Atomic CAN bus telemetry stream recording engine RPM, temperatures, battery voltages, and vibration indices.';

-- ============================================================================
-- 2. fact_service (Dealership Workshop Service Invoices)
-- ============================================================================
-- Grain: 1 row per completed dealership workshop service invoice.
CREATE TABLE IF NOT EXISTS autocare_dw.fact_service (
    service_fact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id VARCHAR(32) UNIQUE NOT NULL,
    vehicle_key INT NOT NULL REFERENCES autocare_dw.dim_vehicle(vehicle_key) ON DELETE RESTRICT,
    dealer_key INT NOT NULL REFERENCES autocare_dw.dim_dealer(dealer_key) ON DELETE RESTRICT,
    date_key INT NOT NULL REFERENCES autocare_dw.dim_date(date_key) ON DELETE RESTRICT,
    visit_date DATE NOT NULL,
    issue TEXT NOT NULL,
    cost NUMERIC(10,2) NOT NULL CHECK (cost >= 0.00),
    _silver_batch_id VARCHAR(64),
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE autocare_dw.fact_service IS 'Dealership maintenance invoices recording service dates, issue descriptions, and total billing amounts.';

-- ============================================================================
-- 3. fact_warranty (OEM Warranty Reimbursement Claims)
-- ============================================================================
-- Grain: 1 row per OEM warranty reimbursement claim.
CREATE TABLE IF NOT EXISTS autocare_dw.fact_warranty (
    warranty_fact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id VARCHAR(32) UNIQUE NOT NULL,
    vehicle_key INT NOT NULL REFERENCES autocare_dw.dim_vehicle(vehicle_key) ON DELETE RESTRICT,
    component_key INT NOT NULL REFERENCES autocare_dw.dim_component(component_key) ON DELETE RESTRICT,
    date_key INT NOT NULL REFERENCES autocare_dw.dim_date(date_key) ON DELETE RESTRICT,
    claim_date DATE NOT NULL,
    amount NUMERIC(10,2) NOT NULL CHECK (amount > 0.00),
    _silver_batch_id VARCHAR(64),
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE autocare_dw.fact_warranty IS 'OEM manufacturer warranty claims recording covered vehicles, failed components, and reimbursed financial amounts.';

-- ============================================================================
-- 4. fact_parts (Dealership Spare Parts Periodic Inventory Snapshot)
-- ============================================================================
-- Grain: 1 row per spare-part SKU (part_id) per dealership (dealer_id) per inventory snapshot date.
CREATE TABLE IF NOT EXISTS autocare_dw.fact_parts (
    parts_fact_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id VARCHAR(32) NOT NULL,
    dealer_key INT NOT NULL REFERENCES autocare_dw.dim_dealer(dealer_key) ON DELETE RESTRICT,
    component_key INT NOT NULL REFERENCES autocare_dw.dim_component(component_key) ON DELETE RESTRICT,
    date_key INT NOT NULL REFERENCES autocare_dw.dim_date(date_key) ON DELETE RESTRICT,
    snapshot_date DATE NOT NULL,
    stock INT NOT NULL CHECK (stock >= 0),
    lead_time INT NOT NULL CHECK (lead_time >= 1),
    _silver_batch_id VARCHAR(64),
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fact_parts_snapshot UNIQUE (part_id, dealer_key, date_key)
);

COMMENT ON TABLE autocare_dw.fact_parts IS 'Dealership spare-parts periodic balance snapshot tracking on-hand stock and supplier lead times by part SKU and component category.';
